### ISSUE TITLE
Typo in the project description

### ISSUE THREAD

**Issue by ck37** [ucberkeley/savio-training-jupyterhub-2017#1]
Hi,

Just a quick note that the github project description says March 8th but I believe the training is planned for tomorrow March 7th - only mentioning because I was confused for a second about which date to believe.

Thanks,
Chris

**Comment by MauriceManning** [comment]
Thanks for the catch Chris. Corrected.

Maurice M. Manning

Berkeley Research Computing <http://research-it.berkeley.edu/brc>

UC Berkeley

**Comment by ck37** [comment]
Sounds good, closing this issue!
